services:
  weaviate:
    image: cr.weaviate.io/semitechnologies/weaviate:1.33.4
    ports:
      - "8080:8080"
      - "50052:50051"
    environment:
      QUERY_DEFAULTS_LIMIT: 25
      AUTHENTICATION_ANONYMOUS_ACCESS_ENABLED: 'true'
      PERSISTENCE_DATA_PATH: '/var/lib/weaviate'
      CLUSTER_HOSTNAME: 'node1'
      ENABLE_MODULES: 'backup-filesystem'
      BACKUP_FILESYSTEM_PATH: '/tmp/backups'
    volumes:
      - ./data/backups/weaviate_backups:/tmp/backups
      - ./data/weaviate_data:/var/lib/weaviate
    networks:
      - law_net
  neo4j:
    image: neo4j:latest
    container_name: my_neo4j
    ports:
      - "7474:7474" 
      - "7687:7687" 
    volumes:
      - ./neo4j/data:/data
      - ./neo4j/logs:/logs
      - ./neo4j/import:/var/lib/neo4j/import
      - ./neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/12345678
      - NEO4J_PLUGINS=["apoc"]
      # - NEO4J_server_memory_heap_initial_size=512M
      # - NEO4J_server_memory_heap_max_size=1G
    networks:
      - law_net
    restart: unless-stopped

  fastapi:
    build: ./python_run
    container_name: fastapi
    ports:
      - "8002:8002"
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      weaviate:
        condition: service_started
      neo4j:
        condition: service_started
    networks:
      - law_net
    restart: unless-stopped

  gradio:
    build: ./python_run
    container_name: gradio
    ports:
      - "7860:7860"
    volumes:
      - .:/app
    working_dir: /app
    command: python src/gradio_app.py
    depends_on:
      fastapi:
        condition: service_started
    networks:
      - law_net
    restart: unless-stopped
    environment:
      - GROQ_API_KEY=${GROQ_API_KEY}
      - FASTAPI_URL=${FASTAPI_URL:-http://fastapi:8002}
      - GROQ_MODEL=${GROQ_MODEL:-llama-3.3-70b-versatile}
    
networks:
  law_net:
    external: true